"""
Django settings for payment_app project.

Generated by 'django-admin startproject' using Django 5.0.

"""
import os
from pathlib import Path

from dotenv import load_dotenv

from payment_app.logger_formatter import ContextFormatter

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", default="PAYMENT_APP_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG_MODE", True)

ALLOWED_HOSTS: list = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # internal
    "cart.apps.CartConfig",
    "shop.apps.ShopConfig",
    "payment.apps.PaymentConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "payment_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "shop", "presentation_layer", "web", "templates"),
            os.path.join(BASE_DIR, "cart", "presentation_layer", "web", "templates"),
            os.path.join(BASE_DIR, "payment", "presentation_layer", "web", "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Custom Context Processors
                "cart.context_processor.cart",
            ],
        },
    },
]

WSGI_APPLICATION = "payment_app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", default="django.db.backends.sqlite3"),
        "NAME": os.getenv("DB_NAME", default=os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        "ATOMIC_REQUESTS": True,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / STATIC_URL

MEDIA_ROOT = os.path.join(BASE_DIR.parents[2], "media", "payment_app")  # One step "higher" than the project directory

MEDIA_URL = "media/"
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Stripe payment settings

STRIPE_PUBLISHABLE_KEY_USD = os.getenv("STRIPE_PUBLISHABLE_KEY_USD")
STRIPE_SECRET_KEY_USD = os.getenv("STRIPE_SECRET_KEY_USD")

STRIPE_PUBLISHABLE_KEY_EUR = os.getenv("STRIPE_PUBLISHABLE_KEY_EUR")
STRIPE_SECRET_KEY_EUR = os.getenv("STRIPE_SECRET_KEY_EUR")
# STRIPE_WEBHOOK_SECRET

DOMAIN = os.getenv("DOMAIN")

CART_SESSION_ID = "cart"


# Logging settings

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "main_format": {
            "()": ContextFormatter,
            "format": "[{asctime}] - {levelname} - {name} - {module}:{funcName}:{lineno} - {message}",
            "datefmt": "%Y-%m-%d %H:%M:%S",
            "style": "{",
        },
    },
    "handlers": {
        "console_handler": {
            "class": "logging.StreamHandler",
            "formatter": "main_format",
            "level": os.getenv("LOG_LEVEL", "INFO"),
        },
        "file_handler": {
            "class": "logging.FileHandler",
            "formatter": "main_format",
            "filename": "inform.log",
            "level": os.getenv("LOG_LEVEL", "INFO"),
        },
    },
    "loggers": {
        "root": {
            "handlers": ["console_handler", "file_handler"],
            "level": "INFO" if not DEBUG else "DEBUG",
            "propagate": False,
        },
        "django": {
            "level": os.getenv("LOG_LEVEL", "INFO"),
            "handlers": ["console_handler", "file_handler"],
            "propagate": False,
        },
        "PIL": {
            "level": "WARNING",
            "handlers": ["console_handler", "file_handler"],
        },
    },
}
